export const REVIEWS = [
    {
        id: 1,
        name: 'St Glx',
        location: 'South London',
        date: '24th Sept, 2023',
        rating: 5,
        text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
    },
    {
        id: 2,
        name: 'John D',
        location: 'East London',
        date: '12th Oct, 2023',
        rating: 4,
        text: 'Great experience overall. The food arrived hot and fresh. Would definitely recommend to anyone looking for a quick and tasty meal in the area.',
    },
    {
        id: 3,
        name: 'Mary K',
        location: 'North London',
        date: '5th Nov, 2023',
        rating: 5,
        text: 'Absolutely loved it! Fast delivery, perfect temperature, and the packaging was great. Will definitely order again soon.',
    },
    {
        id: 4,
        name: 'Alex P',
        location: 'West London',
        date: '18th Nov, 2023',
        rating: 4,
        text: 'Really good food and fast service. The app was easy to use and tracking was accurate. Minor issue with one item missing but resolved quickly.',
    },
    {
        id: 5,
        name: 'Sarah M',
        location: 'Central London',
        date: '2nd Dec, 2023',
        rating: 5,
        text: "Exceptional quality and speed. The staff were incredibly helpful and the food was exactly as described. One of the best delivery experiences I've had.",
    },
    {
        id: 6,
        name: 'Tom B',
        location: 'South East London',
        date: '15th Dec, 2023',
        rating: 4,
        text: 'Very happy with my order. Everything was fresh and delicious. The delivery driver was polite and on time. Will order again for sure!',
    },
]
